package com.vaadin.addon.ipcforliferay.demo.sessionreceiver;

import com.vaadin.addon.ipcforliferay.demo.data.Person;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Table;

/**
 * Demo view that receives Liferay client side inter-portlet messages (from
 * SenderView) and displays their contents in a table. This portlet reads the
 * actual content of the message from (shared) portlet session attributes
 * identified by the key given in the client-side message.
 */
public class SessionReceiverView extends CustomComponent {

    @AutoGenerated
    private AbsoluteLayout mainLayout;
    @AutoGenerated
    private Table table_1;

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    private BeanItemContainer<Person> personContainer;

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */
    public SessionReceiverView() {
        buildMainLayout();
        setCompositionRoot(mainLayout);

        // Create initial container
        createContainer();

    }

    private void createContainer() {
        personContainer = new BeanItemContainer<Person>(Person.class);
        table_1.setContainerDataSource(personContainer);
        addUser("Artur", "Signell", 30);

    }

    void addUser(String firstName, String lastName, int age) {
        personContainer.addBean(new Person(firstName, lastName, age));
    }

    @AutoGenerated
    private AbsoluteLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new AbsoluteLayout();
        mainLayout.setWidth("100%");
        mainLayout.setHeight("240px");

        // top-level component properties
        setWidth("100.0%");
        setHeight("240px");

        // table_1
        table_1 = new Table();
        table_1.setCaption("Current users");
        table_1.setImmediate(false);
        table_1.setWidth("100.0%");
        table_1.setHeight("100.0%");
        mainLayout.addComponent(table_1,
                "top:16.0px;right:0.0px;bottom:0.0px;left:0.0px;");

        return mainLayout;
    }

}
